services:

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: users_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/data/postgres
  adminer:
    image: adminer
    container_name: users_adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "${ADMINER_PORT}:8080"
volumes:
  postgres:
